### PR TITLE
overwrite default material UI selected row background color

### PR DESCRIPTION
**Pull request by studioswong**
## Description

Material-UI by default will apply a new background color to depict a highlighted state for a selected item - this PR is a quick fix to overwrite the highlighted background caused by the default material UI settings for the tree nav sidebar. This also includes an update to some minor CSS changes for the sidebar interaction. 

## Development notes

I have made the relevant CSS changes to overwrite the default material-UI styles, as well as change the default opacity for the sidebar icon interaction. 

## QA notes

The changes for this PR can be tested here: http://kedro-viz-fe.s3-website.eu-west-2.amazonaws.com/fix/fix-mui-selected-color/?data=demo

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

## Legal notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by limdauto** [comment]
Screenshot 2021-09-20 at 02 34 51

Thanks for doing this @studioswong . The preview link is absolutely awesome. I noticed that the clicked state is a bit odd (see screenshot). Is it intentional. Also I noticed that this branch is created on top of 3.14.0. Could we branch off main or at least 3.15.0 instead?

**Comment by studioswong** [comment]
> Screenshot 2021-09-20 at 02 34 51
> 
> Thanks for doing this @studioswong . The preview link is absolutely awesome. I noticed that the clicked state is a bit odd (see screenshot). Is it intentional. Also I noticed that this branch is created on top of 3.14.0. Could we branch off main or at least 3.15.0 instead?

really great spot Lim - I'll put in a fix!

**Review by rashidakanchwala — COMMENTED** [review]
[](url
Screenshot 2021-09-20 at 14 18 57
)

@studioswong  -- when focus mode for one node is already on and i try clicking on other modular pipelines, it gives me this grey-ish background. Is this the expected behavior?

**Comment by studioswong** [comment]
> [](url
> Screenshot 2021-09-20 at 14 18 57
> )
> 
> @studioswong -- when focus mode for one node is already on and i try clicking on other modular pipelines, it gives me this grey-ish background. Is this the expected behavior?

Heya Rashida, I am aware of this problem as this started happening on merging the latest items from the color refactor that was recently merged into main - this will be fixed by updating the color code of the background-color CSS styles for the CSS overwrite. 

Regardless, I will be closing this PR and reopening a new one given the contaminated git commits associated with this PR.

**Pull request closed without merging**
