### PR TITLE
Remove leftover visible layer reducer

### PR DESCRIPTION
**Pull request by rashidakanchwala**
## Description

This was an unused reducer in the visible.js. that was leftover from a previous change. 
We currently use layers.visible reducer to store the state of layers and the app work's fine if we remove the above code. 

## Development notes

Couple of line deletion.

## QA notes

No functionality changes

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

## Legal notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by studioswong — APPROVED** [review]
Hello Rashida!!! Congrats on your first PR on Kedro-viz - good spot!

**Review by richardwestenra — APPROVED** [review]
🎉

**Comment by richardwestenra** [comment]
I can't figure out why CI isn't running on this PR. If we can't get them to run I'm happy for us to merge it if all the tests pass locally, but we should try to get it working first.

@limdauto Do you have any ideas?

**Comment by studioswong** [comment]
> I can't figure out why CI isn't running on this PR. If we can't get CI tests to run I'm happy for us to merge it if all the tests pass locally, but we should ideally try to get it working first.
> 
> @limdauto Do you have any ideas?

@richardwestenra I just merged main and pushed this branch just to see if this could trigger a build on CI and looks like the build is running now. I notice that the previous push didn't trigger any tests on circleCI - I'm not entirely sure if this is due to a permissions issue, might be worth a look?

**Pull request merged**
