### PR TITLE
[KED-2533] Fix/delete description from metadata

### PR DESCRIPTION
**Pull request by rashidakanchwala**
## Description

The docstring is already present in the code panel hence deleting it from metadata panel

## Development notes

The docstring is already present in the code panel hence deleting it from metadata panel
Removed docstring reference from 
- front-end : components, selectors, redux store and the test cases 
- back-end : server.py and test_server.py
 
## QA notes

Ran npm t successfully 

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [x] Added tests to cover my changes

## Legal notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by studioswong — COMMENTED** [review]
LGTM :) Thanks Rashida! 
Only thing is that the description field should ideally only be merged in after the code panel flag is removed (https://jira.quantumblack.com/browse/KED-2534).

Happy to approve this once the above change is merged in main

**Review by richardwestenra — CHANGES_REQUESTED** [review]
Great work! I didn't realise that we were deleting this feature but sounds good to me.

I searched the codebase and there are still a few leftover mentions of `docstring` that need removing:
1. `/src/reducers/nodes.js` on lines 59-61
2. `/src/reducers/reducers.test.js` on line 217
3. `/src/store/normalize-data.js` on lines 29 & 143
4. `/src/utils/random-data.js` on line 200
5. `/src/utils/data/node_task.mock.js` on line 4

We should also check whether we should remove it from the Python server (`package/kedro_viz/server.py`) - @limdauto @MerelTheisenQB should we remove `docstring` from the API node response?

**Review by richardwestenra — CHANGES_REQUESTED** [review]
Great work! I didn't realise that we were deleting this feature but sounds good to me.

I searched the codebase and there are still a few leftover mentions of `docstring` that need removing:
1. `/src/reducers/nodes.js` on lines 59-61
2. `/src/reducers/reducers.test.js` on line 217
3. `/src/store/normalize-data.js` on lines 29 & 143
4. `/src/utils/random-data.js` on line 200
5. `/src/utils/data/node_task.mock.js` on line 4

We should also check whether we should remove it from the Python server (`package/kedro_viz/server.py`) - @limdauto @MerelTheisenQB should we remove `docstring` from the API node response?

**Comment by rashidakanchwala** [comment]
@MerelTheisenQB - I have removed docstring related test case from test_server.py -- I was not super sure if it was relevant to it. def test_node_metadata_endpoint_task_missing_docstring. Please let me know if it's ok

**Review by MerelTheisenQB — APPROVED** [review]
Looks all good on the python side! 🐍 👍  Nice one @rashidakanchwala 😄

**Review by richardwestenra — APPROVED** [review]
Great work!

**Pull request merged**
