### PR TITLE
fix lookup to ensure all layers are present

### PR DESCRIPTION
**Pull request by pascalwhoop**
## Description

To fix a bug that makes layers of encoded datasets not visible

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

## Legal notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by datajoely** [comment]
Nice spot!

**Review by limdauto — APPROVED** [review]
LGTM! Let me look at the unit test to see if we can capture the fix somewhere there.

**Comment by limdauto** [comment]
For some reason, CI doesn't run on this PR. Also I found another bug when testing this fix: https://github.com/quantumblacklabs/kedro-viz/issues/614 -- I will fix both of these on another PR. Will keep you posted.

**Comment by limdauto** [comment]
Issue reproduced and tracked here: https://github.com/quantumblacklabs/kedro-viz/issues/615

**Comment by limdauto** [comment]
@pascalwhoop thanks for the contribution. I have added your fix to https://github.com/quantumblacklabs/kedro-viz/pull/616 and cover with a test (as well as some manual testing).

**Pull request closed without merging**
