### PR TITLE
Fix - update "Kedro Viz" to "Kedro-Viz"

### PR DESCRIPTION
**Pull request by studioswong**
## Description

related PR: https://jira.quantumblack.com/browse/KED-2967

This task is to update our reference of 'Kedro Viz' to 'Kedro-Viz' in line with our naming with the Linux foundation. 

## Development notes

I've searched and udpated references of 'Kedro Viz' to 'Kedro-Viz' in both the JS and Python codebases. 

## QA notes

there should be no changes to the performance of the app as a result of these changes. 

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

## Legal notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by yetudada — APPROVED** [review]
🚀  Thank you!

**Review by tynandebold — CHANGES_REQUESTED** [review]
I think you missed the `<title />` [index file](https://github.com/quantumblacklabs/kedro-viz/blob/main/public/index.html#L12).

**Comment by studioswong** [comment]
> I think you missed the `<title />` in the [index file](https://github.com/quantumblacklabs/kedro-viz/blob/main/public/index.html#L12).

Thanks for spotting this - I remember making this change locally but looks like it wasn't committed and saved. I had just pushed this.

**Review by tynandebold — APPROVED** [review]
Looking good.

**Pull request merged**
